# Generated by Django 3.2.9 on 2021-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars/<django.db.models.fields.related.OneToOneField>', verbose_name='Фото'),
        ),
    ]
