# Generated by Django 3.2.9 on 2021-12-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_profiles',
            field=models.JSONField(blank=True, null=True, verbose_name='Понравившиеся профили'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='app_backend/user_avatars/', verbose_name='Фото'),
        ),
    ]
