# Generated by Django 3.2.9 on 2021-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_auto_20211227_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unliked_profiles',
            field=models.JSONField(blank=True, null=True, verbose_name='Не понравившиеся профили'),
        ),
    ]
