# Generated by Django 3.2.9 on 2021-12-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_profile_unliked_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_profiles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unliked_profiles',
        ),
    ]
