# Generated by Django 3.2.9 on 2021-12-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_backend', '0010_auto_20211227_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_estimations',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_estimations', serialize=False, to='auth.user')),
                ('liked_profiles', models.JSONField(blank=True, null=True, verbose_name='Понравившиеся профили')),
                ('unliked_profiles', models.JSONField(blank=True, null=True, verbose_name='Не понравившиеся профили')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='mutual_sympathy',
            field=models.ManyToManyField(blank=True, to='app_backend.Profile'),
        ),
    ]
