# Generated by Django 3.2.9 on 2021-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_auto_20211227_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_estimations',
            name='liked_profiles',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Понравившиеся профили'),
        ),
        migrations.AlterField(
            model_name='profile_estimations',
            name='unliked_profiles',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Не понравившиеся профили'),
        ),
    ]
