# Generated by Django 3.2.9 on 2021-12-29 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_backend', '0012_auto_20211229_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_estimations',
            new_name='Profile_evaluations',
        ),
    ]
