# Generated by Django 3.2.9 on 2021-12-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0013_rename_profile_estimations_profile_evaluations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_evaluations',
            old_name='unliked_profiles',
            new_name='disliked_profiles',
        ),
    ]
