# Generated by Django 3.2.9 on 2022-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0015_auto_20220108_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгта'),
        ),
    ]
